### PR TITLE
WIP: Menu Integrations

### PR DESCRIPTION
**Pull request by josehbez**
What is it? 
Is the new section that will include app/script and tools ,  which  will make a great gnome pomodoro. 

* Includes new menu called App directory 
* New section App Directory after Download. 
* Is Categorized by type App,  Name App  and Readme

See screenshot below

screenshot-localhost_8000-2021 01 11-11_30_44

screenshot-localhost_8000-2021 01 11-11_31_19

screenshot-localhost_8000-2021 01 11-11_32_06

What do you think of this ?  @gnome-pomodoro/devs 

All comments or feedback is welcome.

Ref: https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/issues/13

### CODE REVIEW

**Comment by kamilprusko** [comment]
I think that "App directory" may be confusing to newcomers. "Extra tools", "Make it your own", "Customize it", "Third-party tools" or "Integrations" would be clearer.

As a viewer I would be interested in topics. So the Categories you listed need to stand out more. It's a good place to add icons.

I like that the description for gnome-pomodoro-tracking is short. I think instead of the picture it would be more useful to list of services with links to wiki pages (like https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/assets/toggl/README.md).

Just my initial impressions.

**Comment by josehbez** [comment]
> I think that "App directory" may be confusing to newcomers. "Extra tools", "Make it your own", "Customize it", "Third-party tools" or "Integrations" would be clearer.
> 
> As a viewer I would be interested in topics. So the Categories you listed need to stand out more. It's a good place to add icons.
> 
> I like that the description for gnome-pomodoro-tracking is short. I think instead of the picture it would be more useful to list of services with links to wiki pages (like https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/assets/toggl/README.md).
> 
> Just my initial impressions.

1 -  **Integrations** would be clearer
2 - Highlight the category with icon
3 - Add Wiki links is great idea

Thanks for your feedback @kamilprusko

**Comment by codito** [comment]
+1 to **Integrations**. More integrations are here: https://github.com/gnome-pomodoro/gnome-pomodoro/wiki/Integration

**Comment by josehbez** [comment]
Review this improvements @gnome-pomodoro/devs 

- [X] Rename  App directory to Integrations  menu
- [X] Category icon using emoji 
- [X] Update Readme GTP

screenshot-localhost_8000-2021 01 12-17_31_10
screenshot-localhost_8000-2021 01 12-17_30_32
screenshot-localhost_8000-2021 01 12-17_24_46

**Comment by kamilprusko** [comment]
I wondered how it could look without the widget from the Download section and with more entries. I sketched this in Inkscape...

integrations

**Comment by josehbez** [comment]
Quick view and user avoid 2 clicks .  I like.

I had categorized because if exists many Integrations the user can find by category. 

I believe we need close this  issue https://github.com/gnome-pomodoro/gnome-pomodoro-website/issues/4 , to continue

**Comment by josehbez** [comment]
https://github.com/gnome-pomodoro/gnome-pomodoro-website/issues/4#issuecomment-782590556

**Pull request closed without merging**
